#!/bin/sh
#
# Logentries agent init script
# Config: /etc/default/logentries-default
# 
#
# chkconfig:   2345 20 80
# description: Logentries agent for log monitoring

### BEGIN INIT INFO
# Provides:          logentries
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $network
# Should-Stop:       $netwrok
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Logentries agent for log monitoring
# Description:       Logentries agent for log monitoring
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

NAME="le-monitordaemon"
EXECNAME="/usr/bin/$NAME"
SERVICENAME="logentries"

[ -e /etc/sysconfig/$SERVICENAME ] && . /etc/sysconfig/$SERVICENAME

lockfile=/var/lock/subsys/$SERVICENAME

start() {
    [ -x $EXECNAME ] || exit 5
    #[ -f $config ] || exit 6
    echo -n $"Starting $SERVICENAME: "
    daemon --check $NAME $EXECNAME
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $SERVICENAME: "
    killproc $NAME
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $NAME
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
	rh_status_q && exit 0
	$1
	;;
    stop)
	rh_status_q || exit 0
	$1
	;;
    restart)
	$1
	;;
    reload)
	rh_status_q || exit 7
	$1
	;;
    force-reload)
	force_reload
	;;
    status)
	rh_status
	;;
    condrestart|try-restart)
	rh_status_q || exit 0
	restart
	;;
    *)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
	exit 2
esac
exit $?
	
