#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# Start method script for the cron service.
#

. /lib/svc/share/smf_include.sh

if [ ! -x /opt/local/bin/python2.7 ]; then
	echo "Python2.7 was not found in /opt/local/bin/"
	exit $SMF_EXIT_ERR_FATAL
fi

if [ -x /opt/local/bin/le ]; then
	/opt/local/bin/python2.7 /opt/local/bin/le monitor
else
	echo "Logentries le executable was not found in /opt/local/bin/"
	exit $SMF_EXIT_ERR_FATAL
fi
exit $SMF_EXIT_OK
